database:
  path: "data/storage.db"
moodle:
  base_url: "https://moodle.innopolis.university/"
  rpm: 120
  max_burst: 120
  user_agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36"
moodle_extender:
  # use internal k8s networking
  base_url: "http://moodle-session-ext.default.svc.cluster.local/"
updater:
  interval: "1h"
bot:
  update_channels:
    - id: -1001842503691 # history passwords
      activity_id: 87610 # prod
    - id: -1001872250726 # history test prod
#      activity_id: 62129 # TC
      activity_id: 87610 # prod
  super_users:
    - 379529027
