database:
  path: "data/storage.db"
moodle:
  base_url: "https://moodle.innopolis.university/"
  rpm: 120
  max_burst: 120
  user_agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36"
moodle_extender:
  base_url: "https://moodle-session-ext.dcnick3.me/"
updater:
  interval: "1h"
bot:
  update_channels:
    - id: -1001727873081 # history test debug
      activity_id: 62129 # TC
