on:
  push:
    branches:
      - master

name: Deploy

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: azure/k8s-set-context@v2
        with:
          method: kubeconfig
          kubeconfig: '${{ secrets.KUBECONFIG }}'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver: kubernetes
          driver-opts: requests.cpu=6,requests.memory=4Gi

      - name: 'Build container'
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: 'ghcr.io/dcnick3/historia:ref-${{ github.sha }}'
          # maybe cache is too slow to be useful...
          # cache-from: type=registry,ref=ghcr.io/dcnick3/historia:buildcache
          # cache-to: type=registry,ref=ghcr.io/dcnick3/historia:buildcache,mode=max

  deploy-prod:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: prod
    steps:
      - uses: actions/checkout@v1

      - uses: azure/k8s-set-context@v2
        with:
          method: kubeconfig
          kubeconfig: '${{ secrets.KUBECONFIG }}'
      - uses: Azure/k8s-deploy@v3.1
        with:
          namespace: 'default'
          manifests: |
            deployment
          images: 'ghcr.io/dcnick3/historia:ref-${{ github.sha }}'